#!/usr/bin/env python3
"""Append deduplicated UIKit/Foundation API lines into func_orign/*.txt."""
from pathlib import Path

RESOURCE = Path(__file__).resolve().parent
ORIGIN = RESOURCE / "func_orign"

SUPPLEMENTS = {
    "uikit_class_func.txt": [
        "+ (UIColor *)blackColor;",
        "+ (UIColor *)darkGrayColor;",
        "+ (UIColor *)lightGrayColor;",
        "+ (UIColor *)whiteColor;",
        "+ (UIColor *)grayColor;",
        "+ (UIColor *)redColor;",
        "+ (UIColor *)greenColor;",
        "+ (UIColor *)blueColor;",
        "+ (UIColor *)cyanColor;",
        "+ (UIColor *)yellowColor;",
        "+ (UIColor *)magentaColor;",
        "+ (UIColor *)orangeColor;",
        "+ (UIColor *)purpleColor;",
        "+ (UIColor *)brownColor;",
        "+ (UIColor *)clearColor;",
        "+ (UIFont *)systemFontOfSize:(CGFloat)fontSize weight:(UIFontWeight)weight;",
        "+ (UIFont *)monospacedSystemFontOfSize:(CGFloat)fontSize weight:(UIFontWeight)weight;",
        "+ (UIFont *)monospacedDigitSystemFontOfSize:(CGFloat)fontSize weight:(UIFontWeight)weight;",
        "+ (UIImage *)imageNamed:(NSString *)name;",
        "+ (UIImage *)imageNamed:(NSString *)name inBundle:(nullable NSBundle *)bundle compatibleWithTraitCollection:(nullable UITraitCollection *)traitCollection;",
        "+ (UIImage *)imageWithContentsOfFile:(NSString *)path;",
        "+ (UIImage *)imageWithData:(NSData *)data;",
        "+ (UIImage *)imageWithData:(NSData *)data scale:(CGFloat)scale;",
        "+ (UIImage *)imageWithCGImage:(CGImageRef)cgImage;",
        "+ (UIImage *)imageWithCGImage:(CGImageRef)cgImage scale:(CGFloat)scale orientation:(UIImageOrientation)orientation;",
        "+ (NSBundle *)mainBundle;",
        "+ (NSBundle *)bundleWithPath:(NSString *)path;",
        "+ (NSBundle *)bundleForClass:(Class)aClass;",
        "+ (NSURL *)URLWithString:(NSString *)URLString;",
        "+ (NSURL *)fileURLWithPath:(NSString *)path;",
        "+ (NSURL *)fileURLWithPath:(NSString *)path isDirectory:(BOOL)isDir;",
        "+ (NSDate *)date;",
        "+ (NSDate *)distantFuture;",
        "+ (NSDate *)distantPast;",
        "+ (NSLocale *)currentLocale;",
        "+ (NSLocale *)autoupdatingCurrentLocale;",
        "+ (NSLocale *)localeWithLocaleIdentifier:(NSString *)ident;",
        "+ (NSTimeZone *)localTimeZone;",
        "+ (NSTimeZone *)timeZoneWithName:(NSString *)name;",
        "+ (NSCalendar *)currentCalendar;",
        "+ (NSCalendar *)autoupdatingCurrentCalendar;",
        "+ (NSCalendar *)calendarWithIdentifier:(NSCalendarIdentifier)calendarIdentifier;",
        "+ (NSNumber *)numberWithBool:(BOOL)value;",
        "+ (NSNumber *)numberWithChar:(char)value;",
        "+ (NSNumber *)numberWithShort:(short)value;",
        "+ (NSNumber *)numberWithInt:(int)value;",
        "+ (NSNumber *)numberWithLong:(long)value;",
        "+ (NSNumber *)numberWithLongLong:(long long)value;",
        "+ (NSNumber *)numberWithFloat:(float)value;",
        "+ (NSNumber *)numberWithDouble:(double)value;",
        "+ (NSNumber *)numberWithInteger:(NSInteger)value;",
        "+ (NSNumber *)numberWithUnsignedChar:(unsigned char)value;",
        "+ (NSNumber *)numberWithUnsignedInt:(unsigned int)value;",
        "+ (NSNumber *)numberWithUnsignedInteger:(NSUInteger)value;",
        "+ (NSString *)stringWithFormat:(NSString *)format, ...;",
        "+ (NSString *)localizedStringWithFormat:(NSString *)format, ...;",
        "+ (NSString *)stringWithCString:(const char *)cString encoding:(NSStringEncoding)enc;",
        "+ (NSData *)dataWithBytes:(const void *)bytes length:(NSUInteger)length;",
        "+ (NSData *)dataWithContentsOfFile:(NSString *)path;",
        "+ (NSData *)dataWithContentsOfURL:(NSURL *)url;",
        "+ (NSArray *)array;",
        "+ (NSArray *)arrayWithObject:(id)anObject;",
        "+ (NSArray *)arrayWithObjects:(const id [])objects count:(NSUInteger)cnt;",
        "+ (NSMutableArray *)arrayWithCapacity:(NSUInteger)numItems;",
        "+ (NSDictionary *)dictionary;",
        "+ (NSDictionary *)dictionaryWithObject:(id)object forKey:(id<NSCopying>)key;",
        "+ (NSMutableDictionary *)dictionaryWithCapacity:(NSUInteger)numItems;",
        "+ (NSSet *)set;",
        "+ (NSSet *)setWithObject:(id)object;",
        "+ (NSMutableSet *)setWithCapacity:(NSUInteger)numItems;",
        "+ (NSIndexSet *)indexSet;",
        "+ (NSIndexSet *)indexSetWithIndex:(NSUInteger)value;",
        "+ (NSIndexSet *)indexSetWithIndexesInRange:(NSRange)range;",
        "+ (NSPredicate *)predicateWithFormat:(NSString *)predicateFormat, ...;",
        "+ (NSPredicate *)predicateWithBlock:(BOOL (^)(id evaluatedObject, NSDictionary<NSString *,id> *bindings))block;",
        "+ (NSFileManager *)defaultManager;",
        "+ (NSUserDefaults *)standardUserDefaults;",
        "+ (NSNotificationCenter *)defaultCenter;",
        "+ (NSOperationQueue *)mainQueue;",
        "+ (NSOperationQueue *)currentQueue;",
        "+ (dispatch_queue_t)mainQueue;",
        "+ (BOOL)isMainThread;",
        "+ (NSThread *)currentThread;",
        "+ (NSThread *)mainThread;",
        "+ (UIApplication *)sharedApplication;",
        "+ (UIScreen *)mainScreen;",
        "+ (UIWindow *)keyWindow;",
        "+ (NSArray<UIWindow *> *)windows;",
        "+ (UIDevice *)currentDevice;",
        "+ (UIImpactFeedbackGenerator *)impactFeedbackGeneratorWithStyle:(UIImpactFeedbackStyle)style;",
        "+ (UINotificationFeedbackGenerator *)notificationFeedbackGenerator;",
        "+ (UISelectionFeedbackGenerator *)selectionFeedbackGenerator;",
        "+ (UIActivityIndicatorView *)appearance;",
        "+ (UILabel *)appearance;",
        "+ (UIButton *)appearance;",
        "+ (UITextField *)appearance;",
        "+ (UITextView *)appearance;",
        "+ (UIImageView *)appearance;",
        "+ (UITableView *)appearance;",
        "+ (UICollectionView *)appearance;",
        "+ (UIScrollView *)appearance;",
        "+ (UIStackView *)appearance;",
        "+ (UISwitch *)appearance;",
        "+ (UISlider *)appearance;",
        "+ (UISegmentedControl *)appearance;",
        "+ (UIProgressView *)appearance;",
        "+ (UIPageControl *)appearance;",
        "+ (UIDatePicker *)appearance;",
        "+ (UIPickerView *)appearance;",
        "+ (UISearchBar *)appearance;",
        "+ (UIToolbar *)appearance;",
        "+ (UITabBar *)appearance;",
        "+ (UINavigationBar *)appearance;",
        "+ (UIBarButtonItem *)appearance;",
    ],
    "uikit_class_instancetype_func.txt": [
        "+ (instancetype)alertControllerWithTitle:(nullable NSString *)title message:(nullable NSString *)message preferredStyle:(UIAlertControllerStyle)preferredStyle;",
        "+ (instancetype)actionWithTitle:(nullable NSString *)title style:(UIAlertActionStyle)style handler:(void (^ __nullable)(UIAlertAction *action))handler;",
        "+ (instancetype)bezierPath;",
        "+ (instancetype)bezierPathWithRect:(CGRect)rect;",
        "+ (instancetype)bezierPathWithOvalInRect:(CGRect)rect;",
        "+ (instancetype)bezierPathWithRoundedRect:(CGRect)rect cornerRadius:(CGFloat)cornerRadius;",
        "+ (instancetype)bezierPathWithRoundedRect:(CGRect)rect byRoundingCorners:(UIRectCorner)corners cornerRadii:(CGSize)cornerRadii;",
        "+ (instancetype)bezierPathWithArcCenter:(CGPoint)center radius:(CGFloat)radius startAngle:(CGFloat)startAngle endAngle:(CGFloat)endAngle clockwise:(BOOL)clockwise;",
        "+ (instancetype)bezierPathWithCGPath:(CGPathRef)CGPath;",
        "+ (instancetype)indexPathForRow:(NSInteger)row inSection:(NSInteger)section;",
        "+ (instancetype)indexPathForItem:(NSInteger)item inSection:(NSInteger)section;",
        "+ (instancetype)indexPathWithIndexes:(NSUInteger[])indexes length:(NSUInteger)length;",
        "+ (instancetype)effectWithStyle:(UIBlurEffectStyle)style;",
        "+ (instancetype)vibrancyEffectWithBlurEffect:(UIBlurEffect *)blurEffect;",
        "+ (instancetype)effectForBlurEffect:(UIBlurEffect *)blurEffect;",
        "+ (instancetype)appearance;",
        "+ (instancetype)appearanceWhenContainedInInstancesOfClasses:(NSArray<Class <UIAppearanceContainer>> *)containerTypes;",
        "+ (instancetype)appearanceForTraitCollection:(UITraitCollection *)trait;",
        "+ (instancetype)storyboardWithName:(NSString *)name bundle:(nullable NSBundle *)storyboardBundleOrNil;",
        "+ (instancetype)viewControllerWithIdentifier:(NSString *)identifier;",
        "+ (instancetype)transitionWithView:(UIView *)view duration:(NSTimeInterval)duration options:(UIViewAnimationOptions)options animations:(void (^ __nullable)(void))animations completion:(void (^ __nullable)(BOOL finished))completion;",
        "+ (instancetype)transitionFlipFromView:(UIView *)fromView toView:(UIView *)toView duration:(NSTimeInterval)duration;",
        "+ (instancetype)keyframeWithRelativeStartTime:(double)frameStartTime relativeDuration:(double)frameDuration animations:(void (^)(void))animations;",
        "+ (instancetype)animatorWithDuration:(NSTimeInterval)duration curve:(UIViewAnimationCurve)curve animations:(void (^)(void))animations;",
        "+ (instancetype)animatorWithDuration:(NSTimeInterval)duration controlPoint1:(CGPoint)point1 controlPoint2:(CGPoint)point2 animations:(void (^)(void))animations;",
        "+ (instancetype)animatorWithDuration:(NSTimeInterval)duration timingParameters:(id<UITimingCurveProvider>)parameters;",
        "+ (instancetype)itemProviderWithObject:(id<NSItemProviderWriting>)object;",
        "+ (instancetype)previewTargetWithContainer:(id<UIDropSession>)container center:(CGPoint)center;",
        "+ (instancetype)previewParameters;",
        "+ (instancetype)previewParametersWithTextLineRects:(NSValue *)rects;",
        "+ (instancetype)configurationWithActions:(NSArray<UIContextualAction *> *)actions;",
        "+ (instancetype)contextualActionWithStyle:(UIContextualActionStyle)style title:(nullable NSString *)title handler:(UIContextualActionHandler)handler;",
        "+ (instancetype)groupedBackgroundConfiguration;",
        "+ (instancetype)plainHeaderFooterConfiguration;",
        "+ (instancetype)plainCellConfiguration;",
        "+ (instancetype)subtitleCellConfiguration;",
        "+ (instancetype)value1CellConfiguration;",
        "+ (instancetype)value2CellConfiguration;",
        "+ (instancetype)filledButtonConfiguration;",
        "+ (instancetype)grayButtonConfiguration;",
        "+ (instancetype)tintedButtonConfiguration;",
        "+ (instancetype)borderedButtonConfiguration;",
        "+ (instancetype)borderlessButtonConfiguration;",
        "+ (instancetype)prominentButtonConfiguration;",
    ],
    "uikit_member_func.txt": [
        "- (void)setNeedsLayout;",
        "- (void)layoutIfNeeded;",
        "- (void)setNeedsDisplay;",
        "- (void)setNeedsDisplayInRect:(CGRect)rect;",
        "- (void)sizeToFit;",
        "- (void)layoutSubviews;",
        "- (void)drawRect:(CGRect)rect;",
        "- (void)didMoveToSuperview;",
        "- (void)willMoveToSuperview:(nullable UIView *)newSuperview;",
        "- (void)didMoveToWindow;",
        "- (void)willMoveToWindow:(nullable UIWindow *)newWindow;",
        "- (void)removeFromSuperview;",
        "- (void)insertSubview:(UIView *)view atIndex:(NSInteger)index;",
        "- (void)addSubview:(UIView *)view;",
        "- (void)insertSubview:(UIView *)view belowSubview:(UIView *)siblingSubview;",
        "- (void)insertSubview:(UIView *)view aboveSubview:(UIView *)siblingSubview;",
        "- (void)bringSubviewToFront:(UIView *)view;",
        "- (void)sendSubviewToBack:(UIView *)view;",
        "- (void)exchangeSubviewAtIndex:(NSInteger)index1 withSubviewAtIndex:(NSInteger)index2;",
        "- (BOOL)isDescendantOfView:(UIView *)view;",
        "- (nullable UIView *)viewWithTag:(NSInteger)tag;",
        "- (void)setContentHuggingPriority:(UILayoutPriority)priority forAxis:(UILayoutConstraintAxis)axis;",
        "- (void)setContentCompressionResistancePriority:(UILayoutPriority)priority forAxis:(UILayoutConstraintAxis)axis;",
        "- (void)addConstraint:(NSLayoutConstraint *)constraint;",
        "- (void)addConstraints:(NSArray<__kindof NSLayoutConstraint *> *)constraints;",
        "- (void)removeConstraint:(NSLayoutConstraint *)constraint;",
        "- (void)removeConstraints:(NSArray<__kindof NSLayoutConstraint *> *)constraints;",
        "- (void)addGestureRecognizer:(UIGestureRecognizer *)gestureRecognizer;",
        "- (void)removeGestureRecognizer:(UIGestureRecognizer *)gestureRecognizer;",
        "- (BOOL)pointInside:(CGPoint)point withEvent:(nullable UIEvent *)event;",
        "- (nullable UIView *)hitTest:(CGPoint)point withEvent:(nullable UIEvent *)event;",
        "- (void)convertPoint:(CGPoint)point toView:(nullable UIView *)view;",
        "- (void)convertPoint:(CGPoint)point fromView:(nullable UIView *)view;",
        "- (void)convertRect:(CGRect)rect toView:(nullable UIView *)view;",
        "- (void)convertRect:(CGRect)rect fromView:(nullable UIView *)view;",
        "- (void)viewWillAppear:(BOOL)animated;",
        "- (void)viewDidAppear:(BOOL)animated;",
        "- (void)viewWillDisappear:(BOOL)animated;",
        "- (void)viewDidDisappear:(BOOL)animated;",
        "- (void)viewWillLayoutSubviews;",
        "- (void)viewDidLayoutSubviews;",
        "- (void)viewDidLoad;",
        "- (void)loadView;",
        "- (void)viewWillTransitionToSize:(CGSize)size withTransitionCoordinator:(id<UIViewControllerTransitionCoordinator>)coordinator;",
        "- (void)willTransitionToTraitCollection:(UITraitCollection *)newCollection withTransitionCoordinator:(id<UIViewControllerTransitionCoordinator>)coordinator;",
        "- (void)presentViewController:(UIViewController *)viewControllerToPresent animated:(BOOL)flag completion:(void (^ __nullable)(void))completion;",
        "- (void)dismissViewControllerAnimated:(BOOL)flag completion:(void (^ __nullable)(void))completion;",
        "- (void)addChildViewController:(UIViewController *)childController;",
        "- (void)removeFromParentViewController;",
        "- (void)beginAppearanceTransition:(BOOL)isAppearing animated:(BOOL)animated;",
        "- (void)endAppearanceTransition;",
        "- (void)reloadData;",
        "- (void)reloadSections:(NSIndexSet *)sections withRowAnimation:(UITableViewRowAnimation)animation;",
        "- (void)insertRowsAtIndexPaths:(NSArray<NSIndexPath *> *)indexPaths withRowAnimation:(UITableViewRowAnimation)animation;",
        "- (void)deleteRowsAtIndexPaths:(NSArray<NSIndexPath *> *)indexPaths withRowAnimation:(UITableViewRowAnimation)animation;",
        "- (void)moveRowAtIndexPath:(NSIndexPath *)indexPath toIndexPath:(NSIndexPath *)newIndexPath;",
        "- (void)selectRowAtIndexPath:(nullable NSIndexPath *)indexPath animated:(BOOL)animated scrollPosition:(UITableViewScrollPosition)scrollPosition;",
        "- (void)deselectRowAtIndexPath:(NSIndexPath *)indexPath animated:(BOOL)animated;",
        "- (void)scrollToRowAtIndexPath:(NSIndexPath *)indexPath atScrollPosition:(UITableViewScrollPosition)scrollPosition animated:(BOOL)animated;",
        "- (void)reloadItemsAtIndexPaths:(NSArray<NSIndexPath *> *)indexPaths;",
        "- (void)insertItemsAtIndexPaths:(NSArray<NSIndexPath *> *)indexPaths;",
        "- (void)deleteItemsAtIndexPaths:(NSArray<NSIndexPath *> *)indexPaths;",
        "- (void)moveItemAtIndexPath:(NSIndexPath *)indexPath toIndexPath:(NSIndexPath *)newIndexPath;",
        "- (void)scrollToItemAtIndexPath:(NSIndexPath *)indexPath atScrollPosition:(UICollectionViewScrollPosition)scrollPosition animated:(BOOL)animated;",
        "- (void)setTitle:(nullable NSString *)title forState:(UIControlState)state;",
        "- (void)setTitleColor:(nullable UIColor *)color forState:(UIControlState)state;",
        "- (void)setImage:(nullable UIImage *)image forState:(UIControlState)state;",
        "- (void)setBackgroundImage:(nullable UIImage *)image forState:(UIControlState)state;",
        "- (void)setAttributedTitle:(nullable NSAttributedString *)title forState:(UIControlState)state;",
        "- (void)addTarget:(nullable id)target action:(SEL)action forControlEvents:(UIControlEvents)controlEvents;",
        "- (void)removeTarget:(nullable id)target action:(nullable SEL)action forControlEvents:(UIControlEvents)controlEvents;",
        "- (void)sendActionsForControlEvents:(UIControlEvents)controlEvents;",
        "- (void)setText:(nullable NSString *)text;",
        "- (void)setAttributedText:(nullable NSAttributedString *)attributedText;",
        "- (void)setFont:(nullable UIFont *)font;",
        "- (void)setTextColor:(nullable UIColor *)textColor;",
        "- (void)setTextAlignment:(NSTextAlignment)textAlignment;",
        "- (void)setNumberOfLines:(NSInteger)numberOfLines;",
        "- (void)setPlaceholder:(nullable NSString *)placeholder;",
        "- (void)setSecureTextEntry:(BOOL)secureTextEntry;",
        "- (void)setImage:(nullable UIImage *)image;",
        "- (void)setHighlightedImage:(nullable UIImage *)image;",
        "- (void)setAnimationImages:(nullable NSArray<UIImage *> *)animationImages;",
        "- (void)startAnimating;",
        "- (void)stopAnimating;",
        "- (void)setContentOffset:(CGPoint)contentOffset animated:(BOOL)animated;",
        "- (void)scrollRectToVisible:(CGRect)rect animated:(BOOL)animated;",
        "- (void)flashScrollIndicators;",
        "- (void)setContentInset:(UIEdgeInsets)contentInset;",
        "- (void)setBounces:(BOOL)bounces;",
        "- (void)setShowsHorizontalScrollIndicator:(BOOL)showsHorizontalScrollIndicator;",
        "- (void)setShowsVerticalScrollIndicator:(BOOL)showsVerticalScrollIndicator;",
        "- (void)setPagingEnabled:(BOOL)pagingEnabled;",
        "- (void)setScrollEnabled:(BOOL)scrollEnabled;",
        "- (void)setAlpha:(CGFloat)alpha;",
        "- (void)setHidden:(BOOL)hidden;",
        "- (void)setOpaque:(BOOL)opaque;",
        "- (void)setClipsToBounds:(BOOL)clipsToBounds;",
        "- (void)setUserInteractionEnabled:(BOOL)userInteractionEnabled;",
        "- (void)setBackgroundColor:(nullable UIColor *)backgroundColor;",
        "- (void)setTintColor:(nullable UIColor *)tintColor;",
        "- (void)setTransform:(CGAffineTransform)transform;",
        "- (void)setFrame:(CGRect)frame;",
        "- (void)setBounds:(CGRect)bounds;",
        "- (void)setCenter:(CGPoint)center;",
        "- (BOOL)becomeFirstResponder;",
        "- (BOOL)resignFirstResponder;",
        "- (BOOL)isFirstResponder;",
        "- (BOOL)canBecomeFirstResponder;",
        "- (BOOL)canResignFirstResponder;",
        "- (void)encodeWithCoder:(NSCoder *)coder;",
        "- (nullable instancetype)initWithCoder:(NSCoder *)coder;",
        "- (NSUInteger)hash;",
        "- (BOOL)isEqual:(id)object;",
        "- (NSString *)description;",
        "- (void)addObserver:(id)observer selector:(SEL)aSelector name:(nullable NSNotificationName)aName object:(nullable id)anObject;",
        "- (void)removeObserver:(id)observer;",
        "- (void)removeObserver:(id)observer name:(nullable NSNotificationName)aName object:(nullable id)anObject;",
        "- (void)postNotificationName:(NSNotificationName)aName object:(nullable id)anObject;",
        "- (void)postNotificationName:(NSNotificationName)aName object:(nullable id)anObject userInfo:(nullable NSDictionary *)aUserInfo;",
        "- (void)setObject:(nullable id)value forKey:(NSString *)defaultName;",
        "- (nullable id)objectForKey:(NSString *)defaultName;",
        "- (void)removeObjectForKey:(NSString *)defaultName;",
        "- (void)synchronize;",
        "- (BOOL)writeToFile:(NSString *)path atomically:(BOOL)useAuxiliaryFile;",
        "- (nullable NSData *)dataWithContentsOfURL:(NSURL *)url;",
        "- (void)appendString:(NSString *)aString;",
        "- (void)appendFormat:(NSString *)format, ...;",
        "- (void)addObject:(id)anObject;",
        "- (void)removeObject:(id)anObject;",
        "- (void)removeAllObjects;",
        "- (void)insertObject:(id)anObject atIndex:(NSUInteger)index;",
        "- (void)replaceObjectAtIndex:(NSUInteger)index withObject:(id)anObject;",
        "- (void)setObject:(id)obj forKeyedSubscript:(id<NSCopying>)key;",
        "- (void)removeObjectForKey:(id)aKey;",
        "- (void)performSelector:(SEL)aSelector withObject:(nullable id)object afterDelay:(NSTimeInterval)delay;",
        "- (void)performSelectorOnMainThread:(SEL)aSelector withObject:(nullable id)arg waitUntilDone:(BOOL)wait;",
        "- (void)invalidate;",
        "- (void)fire;",
        "- (void)impactOccurred;",
        "- (void)notificationOccurred:(UINotificationFeedbackType)notificationType;",
        "- (void)selectionChanged;",
    ],
    "uikit_member_instancetype_func.txt": [
        "- (instancetype)initWithFrame:(CGRect)frame;",
        "- (instancetype)initWithFrame:(CGRect)frame style:(UITableViewStyle)style;",
        "- (instancetype)initWithFrame:(CGRect)frame collectionViewLayout:(UICollectionViewLayout *)layout;",
        "- (instancetype)initWithRootViewController:(UIViewController *)rootViewController;",
        "- (instancetype)initWithNibName:(nullable NSString *)nibNameOrNil bundle:(nullable NSBundle *)nibBundleOrNil;",
        "- (instancetype)initWithImage:(nullable UIImage *)image;",
        "- (instancetype)initWithImage:(nullable UIImage *)image highlightedImage:(nullable UIImage *)highlightedImage;",
        "- (instancetype)initWithBarButtonSystemItem:(UIBarButtonSystemItem)systemItem target:(nullable id)target action:(nullable SEL)action;",
        "- (instancetype)initWithTitle:(nullable NSString *)title style:(UIBarButtonItemStyle)style target:(nullable id)target action:(nullable SEL)action;",
        "- (instancetype)initWithCustomView:(UIView *)customView;",
        "- (instancetype)initWithTarget:(nullable id)target action:(nullable SEL)action;",
        "- (instancetype)initWithActivityIndicatorStyle:(UIActivityIndicatorViewStyle)style;",
        "- (instancetype)initWithProgressViewStyle:(UIProgressViewStyle)style;",
        "- (instancetype)initWithFrame:(CGRect)frame primaryAction:(nullable UIAction *)primaryAction;",
        "- (instancetype)initWithConfiguration:(UIButtonConfiguration *)configuration;",
        "- (instancetype)initWithText:(NSString *)text;",
        "- (instancetype)initWithAttributedText:(NSAttributedString *)attributedText;",
        "- (instancetype)initWithString:(NSString *)string attributes:(nullable NSDictionary<NSAttributedStringKey,id> *)attrs;",
        "- (instancetype)initWithString:(NSString *)string;",
        "- (instancetype)initWithData:(NSData *)data encoding:(NSStringEncoding)encoding;",
        "- (instancetype)initWithContentsOfFile:(NSString *)path;",
        "- (instancetype)initWithContentsOfURL:(NSURL *)url;",
        "- (instancetype)initWithObjects:(const id [])objects count:(NSUInteger)cnt;",
        "- (instancetype)initWithArray:(NSArray *)array;",
        "- (instancetype)initWithArray:(NSArray *)array copyItems:(BOOL)flag;",
        "- (instancetype)initWithDictionary:(NSDictionary *)otherDictionary;",
        "- (instancetype)initWithDictionary:(NSDictionary *)otherDictionary copyItems:(BOOL)copyItems;",
        "- (instancetype)initWithSet:(NSSet *)set;",
        "- (instancetype)initWithCapacity:(NSUInteger)numItems;",
        "- (instancetype)initWithURL:(NSURL *)URL;",
        "- (instancetype)initWithURL:(NSURL *)URL cachePolicy:(NSURLRequestCachePolicy)cachePolicy timeoutInterval:(NSTimeInterval)timeoutInterval;",
        "- (instancetype)initWithTimeIntervalSinceNow:(NSTimeInterval)seconds;",
        "- (instancetype)initWithTimeInterval:(NSTimeInterval)secsToBeAdded sinceDate:(NSDate *)date;",
        "- (instancetype)initWithFireDate:(NSDate *)date interval:(NSTimeInterval)interval target:(id)target selector:(SEL)selector userInfo:(nullable id)userInfo repeats:(BOOL)repeats;",
        "- (instancetype)initWithName:(NSString *)name object:(nullable id)object userInfo:(nullable NSDictionary *)userInfo;",
        "- (instancetype)initWithActivityItems:(NSArray *)activityItems applicationActivities:(nullable NSArray<__kindof UIActivity *> *)applicationActivities;",
        "- (instancetype)initWithActivityItems:(NSArray *)activityItems applicationActivities:(nullable NSArray<__kindof UIActivity *> *)applicationActivities excludedActivityTypes:(nullable NSArray<UIActivityType> *)excludedActivityTypes;",
        "- (instancetype)initWithBarButtonSystemItem:(UIBarButtonSystemItem)systemItem menu:(UIMenu *)menu;",
        "- (instancetype)initWithPrimaryAction:(UIAction *)action;",
        "- (instancetype)initWithTitle:(NSString *)title image:(nullable UIImage *)image identifier:(nullable UIActionIdentifier)identifier handler:(UIActionHandler)handler;",
        "- (instancetype)initWithTitle:(NSString *)title image:(nullable UIImage *)image identifier:(nullable UIActionIdentifier)identifier discoverabilityTitle:(nullable NSString *)discoverabilityTitle attributes:(UIMenuElementAttributes)attributes state:(UIMenuElementState)state handler:(UIActionHandler)handler;",
        "- (instancetype)initWithTitle:(NSString *)title children:(NSArray<UIMenuElement *> *)children;",
        "- (instancetype)initWithTitle:(NSString *)title image:(nullable UIImage *)image identifier:(nullable UIMenuIdentifier)identifier options:(UIMenuOptions)options children:(NSArray<UIMenuElement *> *)children;",
        "- (instancetype)initWithItemProvider:(NSItemProvider *)itemProvider;",
        "- (instancetype)initWithItemProvider:(NSItemProvider *)itemProvider previewProvider:(NSItemProviderPreviewProvider)previewProvider;",
        "- (instancetype)initWithItemProvider:(NSItemProvider *)itemProvider previewProvider:(NSItemProviderPreviewProvider)previewProvider actionProvider:(NSItemProviderLoadActionProvider)actionProvider;",
    ],
}


def append_dedup(target: Path, lines: list[str]) -> tuple[int, int]:
    existing = set()
    if target.exists():
        for raw in target.read_text(encoding="utf-8").splitlines():
            line = raw.strip()
            if line:
                existing.add(line)
    added = 0
    skipped = 0
    with target.open("a", encoding="utf-8") as fh:
        for line in lines:
            line = line.strip()
            if not line or line in existing:
                skipped += 1
                continue
            existing.add(line)
            fh.write(line + "\n")
            added += 1
    return added, skipped


def main():
    for name, lines in SUPPLEMENTS.items():
        path = ORIGIN / name
        before = len(path.read_text(encoding="utf-8").splitlines()) if path.exists() else 0
        added, skipped = append_dedup(path, lines)
        after = len(path.read_text(encoding="utf-8").splitlines())
        print(f"{name}: {before} -> {after} (+{added}, skip {skipped})")


if __name__ == "__main__":
    main()

